//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageCustomers.Models.ManageCustomersModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public int CustomerId { get; set; }
        public string Email { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
